

<footer>
	
	<div class="twelve columns validate-link"><a href="http://validator.w3.org/check?uri=referer" target="_blank">HTML5 Valid</a>&nbsp; <span><!--#echo var="DATE_LOCAL" --></span></div>

</footer>

<script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>
    <script>
    
        (function($){
            
            $(document).ready(function(){
                var minWidthMenuIsShown=550;

                $(".js-with-popup").on('click',function(){
                    $('.js-with-popup .subclass').toggle(320); 
                });
            });
            
            
            
        }(jQuery));
        
    </script>         
    
