<div class="top">
    <nav>
        <ul><li><a href="http://blogcomp1950.tumblr.com/">Blog</a></li><li><a href="about.shtml">About</a></li></ul>
    </nav>
</div>
<div class="row main">
   <div class="logo four columns">
        <img src="images/logo.png" alt="logo">
   </div>
   <nav class="eight columns main-nav">
       <ul>
           <li><a href="index.shtml">Home</a></li>
           <li class="js-with-popup"><a href="#">Lessons</a>
               <div class="subclass">
               <ul><li><a href="week1.shtml">Week1</a></li><li>Week2</li><li>Week3</li><li>Week4</li></ul></div>
           </li>
           <li><a href="project.shtml">Project</a></li>
           <li><a href="accounts.shtml">Account</a></li>
       </ul>
   </nav>

</div>