<aside class="three columns sidebar" role="complementary">
    <div class="form-wrapper">
     <form role="search">
      <input type="search" placeholder="Need to find something?">
    </form>

    </div>
    <nav role="navigation">
        <li><a href="/">Intro</a></li>
        <li><a href="/rationale-page.shtml">Rationale</a></li>
        <li><a href="/webapp/">Demo</a></li>
        <li><a href="http://www.tumblr.com/icaf-guru/">News</a></li>
    </nav>
</aside>