  <footer class="row-full">
    <div class="one column">
 	</div>
    <div class="four columns important-links">
		<h4>Important Links</h4>
		<div>
		<ul>
		<li>
		<address><span class="website"><a href="https://trello.com/b/GbuQ5V2D/bcit-wdd2">Trello: WDD Project Board</a></span></address>
		</li>
		<li>
		<address><span class="website"><a href="https://github.com/chrisbautista/icaf">Github Page</a></span></address>
		</li>
		<li><address><span class="website"><a href="https://projects.invisionapp.com/d/main#/console/6813007/146076211/preview">Invision</a></span></address></li>
		<li><address><span class="website"><a href="/webapp/">Demo</a></span></address></li>
		</ul>
			
		</div>
	</div>

	<div class="four columns contributors">
		<h4>Contributors</h4>
		<div>
		<ul>
		    <li><address><span class="author">Bautista, Chris A.</span></address></li>
		    <li><address><span class="author">Kuo, Alex</span></address></li>
		    <li><address><span class="author">Mancilla, Fernando</span></address></li>
		</ul>
			
		</div>
	</div>
	<div class="three columns about">
		<h4>About</h4>
		<div >
			<p>
				Project assigned by Alistair Calder to enable us to find our methodology and use the lessons he taught in the class.
			</p>
		</div>
	</div>
	<div class="row"></div>
		<div class="row-fluid validate-link"><a href="http://validator.w3.org/check?uri=referer" target="_blank">HTML5 Valid</a>
	    <span><!--#echo var="DATE_LOCAL" --></span></div>
</footer>