       <header class="row-full">

            <div class="two columns title-logo">iCAF</div>

            <nav class="nine columns " role="navigation">
                <ul>
                    <li><a href="/">Intro</a></li>
                    <li><a href="/rationale-page.shtml">Rationale</a></li>
                    <li><a href="/webapp/">Demo</a></li>
                    <li><a href="http://www.tumblr.com/icaf-guru/">News</a></li>
                    
                </ul>
            </nav>

        </header>