       <header class="row-full">

            <div class="two columns title-logo">iCAF</div>

            <nav class="nine columns " role="navigation">
                <ul>
                    <li><a href="index.shtml">Home</a></li>
                    <li><a href="intro.shtml">Introduction</a></li>
                    <li><a href="rationale.shtml">Rationale</a></li>
                    <li><a href="webapp/">Demo</a></li>
                    <li><a href="http://www.tumblr.com/icaf-guru/">News</a></li>
                    
                </ul>
            </nav>

        </header>